# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07361206921eb2f91fb0baef281e302395b51356cf9f2cb193b57f35fe41828f23be170cf3344d14a1b19137703544bd44e18106eda98a539aaa51dac3afe37b

test:
  secret_key_base: 1c6681611aa06e9219282d72e57b03411f4f25ecac6716cdeb765f9856ff632e483df486091c35624ae5194e4de0c94d41b200bdb35a68fb4513b0e3d0679e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
